name: native_network_plugin
description: A network plugin which allows us to make get requests.
version: 0.0.1

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.combsoko.genba.native_network_plugin
        pluginClass: NativeNetworkPlugin
